"use client";
import React, { Fragment, useEffect } from "react";
import { useRouter } from "next/router";
import Header from "./header";
import Footer from "./footer";
import "./globals.css";
import { app, getApps } from "@/store/firebase";
import { AuthContextProvider } from "@/store/authContext";
import { Noto_Sans_KR } from "next/font/google";

const noto = Noto_Sans_KR({
  weight: "500",
  subsets: ["latin"],
});

export const metadata = {
  title: "Next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const router = useRouter();

  // 컴포넌트가 마운트될 때 Firebase 초기화
  useEffect(() => {
    if (!getApps().length) app;
  }, []);
  return (
    <html lang="ko">
      <body className={noto.className}>
        <AuthContextProvider>
          {router.pathname === "/login" ? (
            <main className="flex">{children}</main>
          ) : (
            <Fragment>
              <Header />
              <main className="flex">{children}</main>
              <Footer />
            </Fragment>
          )}
        </AuthContextProvider>
      </body>
    </html>
  );
}
